nodepa/seedlingo

- .github/FUNDING.yml
Because supporters should get a smooth and good experience,
- change the sponsor link to a prettier format
- I agree to license these contributions to the public under Seedling's
[LICENSE](https://github.com/nodepa/seedling/blob/main/LICENSE.md)
> docs: Prettify sponsor link

- docs/_config.yml
Because the docs should serve as a portal to the project
including documentation
- change the Jekyll theme to "Minimal Mistakes" for more flexibility
- I agree to license these contributions to the public under Seedling's
[LICENSE](https://github.com/nodepa/seedling/blob/main/LICENSE.md)
> docs: Change docs theme

- .gitmessage
- LICENSE.md
- docs/_config.yml
Because having two licenses in the base LICENSE file confuses GitHub,
and it's recommended to note multiple licenses in the README anyway,
- reformat the base LICENSE file to only quote the MIT license
> docs: Reformat license file

- docs/_config.yml
- docs/_includes/footer.html
Because users may be using ad-blockers,
and at least some ad-blockers hide the link to the privacy policy,
- remove the identifier that triggers the ad-blocker
- remove the icon on the privacy policy link
> docs: Remove ad-blocker trigger

- docs/_config.yml
Because the privacy link is relative,
it does not reach the actual url when showing a sub-page.
- make the privacy link absolute
> docs: Fix privacy link when on sub-page

- .github/CONTRIBUTING.md
- README.md
Because GlobalSeedling.com is live with the documentation for Seedling
- update documentation references to refer to GlobalSeedling.com
Resolves #69
> docs: Fix reference to documentation

- app/src/Lessons/ContentPackTypes.ts
Because the outdated comment may confuse content devs,
- amend the comment to reference the correct path to content
> refactor: Fix path to content ref in comment

- app/package-lock.json
Because users should be protected from the consequences of using
insecure dependencies,
- bump jsonpointer to 5.0.0
> fix: Bump jsonpointer to 5.0.0 for security

- .github/SUPPORT.md
- .github/workflows/docs.yml
- README.md
Because switching to Vuepress came with a few hicups,
- add configuration to deploy a .nojekyll file
to prevent Github from running the default Jekyll workflow
- update the path to the logo since doc-assets live elsewhere now
- update support-documentation
to direct doc-seekers to globalseedling.com
> docs: Fix missing .nojekyll and changed image path

- README.md
Because contributors should have easy access to correct documentation,
- fix the links from the README to globalseedling.com docs
> docs: Update readme links to globalseedling.com

- app/commitlint.config.js
Because the commit certification can appear both in body and footer,
- fix the commitlint rule to also evaulate the footer
> infra: Fix commitlint rule certification in footer

- app/commitlint.config.js
Because commitlint's body-leading-blank rule doesn't account for comments as possible lines between header and body,
- add a custom plugin rule that checks if the first lines after the header are either comments or blanks, ensuring that there are at least one blank before the body proper.
> infra: Re-add commitlint body-leading-blank

- .github/pull_request_template.md
- .gitmessage
- app/commitlint.config.js
Because having to delete pull request template text when creating a PR on GitHub is slow and cumbersome, yet it has been necessary due to the structure of the PR template, and because consistency between commit message template, commitlint rules, PR template and commit message examples reduces developer friction by managing developer expectations better,
- upate the PR template and make all of it a comment, so that forgetting to delete it will leave it not rendered on GitHub, while leaving guidance that can be uncommented if needed
- update the .gitmessage commit message template with consistent certification language
- update commitlint.config.js with better phrasing …
> infra: Update templates for commit messages and pull requests

- README.md
- docs/index.md
Because content developers and users should have easy access to the app
- add instructions on how to download the Android app for a fully offline experience
> docs: Add instructions to download Android app

- .github/workflows/docs.yml
- docs/package-lock.json
- docs/package.json
Because GitHub has updated the default node version and our deployment workflow fails
- update the workflow with the latest version of actions
- set the node version used to latest long term support version
> docs: Update docs deployment workflow actions

- app/src/Comprehension/components/ComprehensionExercise.vue
Because Safari & iOS users should have feature and quality parity,
- add a soft line break between `word units` of a comprehension text, where a `word unit` is one or more characters, possibly followed by a punctuation, that constitue a common unit in the presentation to encourage line breaks _after_ punctuation, and also _not_ in the middle of a word of multiple characters (if so defined in the content's word list).
Safari treats CSS line break and word wrap rules in such a way that we need to add a specific tag (`<wbr />`) in the HTML output to handle this use case consistently.
- I license these contributions to the public under …
> fix: Break lines in comprehension exercise text in Safari

- app/src/Comprehension/ComprehensionTypes.ts
- app/src/Comprehension/components/ComprehensionExercise.vue
- app/src/Lessons/ContentTypes.ts
- app/src/Lessons/ExerciseProvider.ts
- content/Lesson12.json
- content/Lesson17.json
- content/Lesson21.json
Because the instructions at the start
of the comprehension exercise stage practicing new words
is so similar to the instruction when showing the first related exercise
- introduce a flag that can be set on each stage in the content spec
that prevents autoplaying instructions when entering that stage
- alway prevent autoplaying instructions for the PracticeNewWords stage
- allow for playing instructions for both non-autoplaying stages
and for the PracticeNewWords stage upon user request/interaction
- I license these contributions to the public under Seedling's [LICENSE](https://github.com/nodepa/seedling/blob/main/LICENSE.md) and have the …
> fix: Postpone instruction for comprehension word practice

- app/src/common/directives/InstructionsDirective.ts
Because we want the app to run smoothly and not eat unneccessary memory,
- add unmounting of the instruction badge when unmounting the component the directive is applied to
> fix: Unmount instruction badge when unmounting parent

- app/src/Comprehension/components/ComprehensionExercise.vue
- app/src/Lessons/ExerciseProvider.ts
- app/src/Matching/components/MatchingExercise.vue
Because circumventing isolation in the DOM can lead to unexpected bugs,
- replace one instance of such a workaround with the proper use of assigning values to the css var that ionic uses to set the relevant value on the component
> refactor: Use css var to affect shadow root

- app/src/views/ReviewSession.vue
Because we use icons to represent digits in numbers, and combine multiple icons to represent large numbers, like 65,
- display multiple icons on the same line until the line owerflows, rather than vertically with one icon per line
Resolves #437
> fix: Display consecutive icons in review horizontaly

- content/Lesson09.json
Because it is confusing when an exercise has two logically and semantically correct answers,
while only one of those is allowed as the correct answer,
- clean up the content specification for lesson 9 and 10 to remove ambiguity of answer options
Resolves #438 …
> content: Fix reasonableness in L9

- .github/pull_request_template.md
- .gitmessage
- app/commitlint.config.ts
Because we have tasks that are better described as chores than infrastructure, as well as missing a commit type for reverting,
- add chore and revert as new commit types,
- remove infra as commit type (replaced by chore) …
> docs: Update commit conventions and linting

- app/src/views/ExerciseSession.vue
Because users may get confused
by being automatically returned to the main menu,
we should keep them in an exercise session for longer. However, the exercise sessions should not be so long that users lose interest.
- change the number of repetitions in a session from 5 to 10
please (re-)write the pull request …
> feat: Increase repetitions from 5 to 10

- docs/.vuepress/public/favicon/favicon.svg
- docs/vuepress.config.ts
Because we want to avoid confusing users with unneccessary variation,
- update the favicon of docs to use the same favicon as the app
> docs: Update favicon

- docs/.vuepress/public/robots.txt
- docs/package-lock.json
- docs/package.json
- docs/vuepress.config.ts
Because we'd like Seedlingo.com to be more discoverable
- add a seo plugin that adds open graph and other metadata
- add a sitempat plugin that autogenerates a sitemap
- add a robots.txt file to allow crawlers
> docs: Add seo, sitemap and robots.txt

- app/android/app/build.gradle
- app/package-lock.json
- app/package.json
- app/src/AppHeader/components/AppHeader.vue
Because version number and build number are joined without a space,
- inject an underscore between them
> fix: Inject underscore before build number

- app/android/app/build.gradle
- app/package-lock.json
- app/package.json
- app/src/common/plugins/PlausibleAnalytics.ts
Because an oversight led to the analytics tool not reporting version and build when loading the web app,
- add tracking of version and build number when not in mobile app
> fix: Track version and build when not mobile app

- app/android/app/build.gradle
- app/package-lock.json
- app/package.json
- app/src/Matching/components/MatchingExercise.vue
- app/src/MultipleChoice/components/MultipleChoiceExercise.vue
- app/src/views/ReviewSession.vue
- content/ContentSpec.json
Because pictures would fill the width of their button, pictures with aspect ration < 1.5 would become very tall, and the button would expanding and push buttons below off screen.
- constrain the picture within the button by enforcing a fixed height to the button by dividing the available vertical space by the number of button rows
> fix: Constrain pictures to enforce symetrically sized buttons

- docs/content/content-spec.md
- docs/package-lock.json
- docs/package.json
Because docs should reflect current app and content format version,
- update docs to reference format version 1.3.0
> docs: Update format version to 1.3.0

- app/src/AppHeader/components/AppHeader.vue
- app/src/BottomNavigationBar/components/ToggleInstructionsButton.vue
- app/src/Cloze/ClozeTypes.ts
- app/src/Cloze/components/ClozeExercise.vue
- app/src/Cloze/data/SingleClozeTestData.ts
- app/src/Matching/MatchingTypes.ts
- app/src/MultipleChoice/data/ExplanationMultipleChoiceTestData.ts
- app/src/common/components/ExerciseButton.vue
- app/src/common/components/InstructionsBadge.vue
- app/src/common/router/index.ts
- app/src/common/store/InstructionsModeStore.ts
- app/src/common/store/StoreTypes.ts
- app/src/main.ts
- app/src/views/ReviewSession.vue
Because we should only use relative import paths within "modules"
- update some imports to use a project-root relative import path by prefixing "@/" that will be replaced with the project root on build
> fix: Set project-root relative import refs

- app/android/app/build.gradle
- app/package-lock.json
- app/package.json
- app/src/Matching/components/MatchingExercise.vue
- app/src/views/ReviewSession.vue
Because we want to keep information on screen
so that users won't have to scroll
(as long as the content can be kept at a legible size regardless)
- change the styling of the matching exercise to ensure it stays contained within its designated area when displayed within a comprehension exercise
> fix: Contain matching exercise within comprehension exercise

- docs/index.md
Because an upgrade to tooling broke the What is Seedlingo-button, so that it became unresponsive to clicking,
- change the link address of the button to make it responsive again
> docs: Fix link on What is Seedlingo-button

- app/tests/unit/UnitValidation.test.ts
Because a content developer should be able to see
which content IDs are identified as not unique
when running the validator,
- add a test that will trigger on non-unique IDs,
which leads to the system outputting the non-unique IDs
> test: Improve error reporting on non-unique IDs

- app/src/common/components/ExerciseButton.vue
Because we should support alphabetic scripts,
and display them as specified in the content spec, but Ionic Framework applies upper-casing
to any text presented in a button,
we have to override this behaviour.
- remove the text decoration that Ionic Framework applies to buttons on our custom extended buttons
> feat: Display alphabetic scripts capitalized as specced

- app/tests/e2e/specs/review.ts
Because content has been translated into English,
but an end-to-end test of the review system
evaluates the presence of the first two words of the first unit, failing the test because those words are now in English.
This commit will update the relevant test
to check for the English translation instead.
> test: Update test depending on translated content

- app/src/Cloze/components/ClozeExercise.vue
- app/src/Comprehension/components/ComprehensionExercise.vue
- app/src/Matching/components/MatchingExercise.vue
- app/src/MultipleChoice/components/MultipleChoiceExercise.vue
- app/src/common/utils/CalcFontSize.ts
- app/src/views/ReviewSession.vue
- app/tests/e2e/specs/matching.ts
When creating content in a language that uses a writing system with an alphabet script rather than a logography,
answer options tend to consist of more symbols.
This surfaces a need to handle scaling of both alpabetic scripts (which tend to form words that are significantly wider than tall, in particular in languages that use inflection or compounding) and logogrphic scrips (which can form words that are taller than wide, i.e. one character words).
Since CSS does not allow us to simply define that a paragraph should fit the container it is placed in,
i.e. scale up to fill the container if the text is one word or scale down to fit within the container if the text is very long, we need sensible parameters for font size to:
- display short text filling at least 50% of its container
- display …
> fix: Amend resize of answer option text

- app/src/Content/ExerciseProvider.ts
- app/src/Matching/components/MatchingExercise.vue
Because content can be specified
to allow matching and multple choice exercises
with phrases/explanations to match/interpret
without corresponding audio for the phrases/explanations, the app should not expect that audio to exist
and should not attempt to play that audio when it does not exist.
- update the exercise generator to avoid adding audio when it is missing from the content specification
- update the matching exercise presentation to not attempt to play missing audio
> fix: Handle missing explanation audio gracefully

- app/src/Cloze/ClozeTypes.ts
- app/src/Cloze/components/ClozeExercise.vue
- app/src/Comprehension/ComprehensionTypes.ts
- app/src/Comprehension/components/ComprehensionExercise.vue
- app/src/Content/ExerciseProvider.ts
- app/src/common/types/ContentTypes.ts
- app/tests/e2e/specs/cloze.ts
Because the app was initially developed for Simplified Chinese, we chose to not present spaces between words.
We will now introduce support for alphabetic scripts.
- add optional content spec flags for exercise text where spaces should be added
- add spaces when presenting explanations, cloze texts and comprehension texts if the space-injection flags have been set
> feat: Add option to present spaces between words

- app/src/Cloze/components/ClozeExercise.vue
- app/src/Comprehension/components/ComprehensionExercise.vue
- app/src/UnitsMenu/components/UnitsMenu.vue
Because we are adding content using alphabet scripts, and justified text tend to be harder to read,
- change text aligning to left for left-to-right and right for right-to-left languages (i.e. text-align: start)
- improve presenetation of the units menu to properly center text
> feat: Improve text aligning for alphabet scripts

- app/package-lock.json
- app/package.json
- app/src/Cloze/components/ClozeExercise.vue
- app/src/Comprehension/components/ComprehensionExercise.vue
- app/src/Content/ExerciseProvider.ts
- app/src/common/types/ContentTypes.ts
- app/tests/e2e/specs/cloze.ts
Because we add spaces to cloze and comprehension exercises without checking the relevant flags in the spec,
we always add spaces between words indiscriminately. The presentation of text should instead add spaces only when specified.
- update the exercise generator to actually pass the inject spaces-flag on to the renderer
- update the renderer to more robustly present spaces
> fix: Remove erroneously added non-specced spaces

- app/android/app/build.gradle
- app/package-lock.json
- app/package.json
- app/src/Comprehension/components/ComprehensionExercise.vue
- app/src/common/components/HoneyBeeInstructor.vue
Because the instructor text sometimes gets covered by the answer options in comprehension exercises,
- ensure that the text has enough room and scales correctly
> fix: Prevent hiding of instructor text behind options

- app/android/app/build.gradle
- app/package-lock.json
- app/package.json
- app/vite.config.ts
Because the legacy api of Dart Sass is deprecated,
- configure Vite to use the modern compiler api instead
> fix: Configure vite to use modern sass compiler
