app/src/App.vue
app/src/Footer/components/Footer.vue
app/src/router/index.ts
app/src/views/Home.vue
app/src/views/Privacy.vue
docs/_config.yml
docs/_pages/privacy-policy.md

Because our users deserve to be treated with respect,
and GDPR requires some disclosure if we start collecting PII
- add a privacy policy to Seedling (liaizhongzi.com/种字.com)
- add a privacy policy to docs (GlobalSeedling.com)
- I agree to license these contributions to the public under Seedling's
[LICENSE](https://github.com/nodepa/seedling/blob/main/LICENSE.md)

docs: Add privacy statement

---

.github/workflows/codeql-analysis.yml

Because we want to write high quality code,
- add the configuration for a GitHub action using CodeQL to analyse repo code

infra: Create code quality GitHub workflow

---

docs/index.md

Signed-off-by: toshify 4579559+toshify@users.noreply.github.com

docs: Fix typo

---

app/src/Cloze/ClozeTypes.ts
app/src/Cloze/components/Cloze.vue
app/src/Cloze/data/MultiClozeTestData.ts
app/src/Cloze/data/SingleClozeTestData.ts
app/src/Lessons/ExerciseProvider.test.ts
app/src/Lessons/ExerciseProvider.ts
app/src/views/Session.vue

Because the codebase should be easy to maintain
- refactor the presentation of single- and multicloze exercises

refactor: Simplify cloze code

---

app/android/app/build.gradle
app/android/app/release/output-metadata.json
app/android/build.gradle

Because we want to distribute updates to Seedling as Android app,
- update the version of the Android app in the build config
to correspond to Seedling's version

infra: Update Android version

---

app/index.html
app/src/main.ts
app/vite.config.ts

fix: Change html lang to cmn=mandarin

---

app/src/main.ts

fix: Remove unnecessary registerSW

---

app/index.html
app/src/App.vue
app/src/assets/registerServiceWorker.ts
app/vite.config.ts

fix: Fix pwa auto-reload

---

app/android/app/build.gradle
app/package-lock.json
app/package.json

Because bumping the version number allows users to know if they have the latest version installed
- bump the package.json and Android build version …

infra: Update version to prep Android build

---

app/android/app/build.gradle
docs/index.md

TITLE format:
└── feat, fix, refactor, style, docs, test, content or infra
MESSAGE format:
**Motivation - Why is this …

infra: Update output name of Android apk

---

docs/get-started/get-started.md

Because the port was incorrect
- add the correct port
n/a
TITLE format:
└── feat, fix, refactor, style, docs, test, content or infra
MESSAGE format:
**Motivation - Why …

docs: Update localhost port in get-started.md

---

docs/.vuepress/styles/index.scss
docs/.vuepress/theme/Layout.vue
docs/architecture/architecture.md
docs/content/content-spec.md
docs/content/content-validation.md
docs/content/content.md
docs/get-started/get-started.md
docs/index.md
docs/package-lock.json
docs/package.json

Because the documentation should be useful and dependable by being fully up to date and reflect current functionality,
- bring docs back in sync with current functionality

docs: Update documentation to reflect app-changes

---

app/package-lock.json
app/package.json
app/src/assets/registerServiceWorker.ts

Because users and developers should be safe from security vulns,
- update Cypress to v13
- update other tooling to most recent version
TITLE format:
└── feat, fix, …

infra: Update dependencies to mitigate vulns

---

app/package-lock.json
app/package.json
docs/package-lock.json

Because of a security vuln in postcss,
- update all dependencies, including those relying on postcss upstream

infra: Update dependencies

---

app/src/common/directives/InstructionsDirective.ts

Because the createApp() function has more memory overhead and also pollutes the Vue dev-tools with (currently) 36+ app-instances,
- replace the use of createApp() in the InstructionsDirective with h() (aka createVNode())

refactor: Replace createApp with h() aka createVNode()

---

.github/ISSUE_TEMPLATE/bug_report.md

Because contributors should have a smooth experience dealing with as little confusion as possible
- update the bug report template for issues to make some inline instructions into html comments preventing the instructions from displaying as part of the issue …

feat: Add feature (use imperative mood)

---

.github/CONTRIBUTING.md
README.md
app/README.md
app/index.html
app/src/views/PrivacyPolicy.vue

Because a domain name previously used has lapsed,
- remove any references to the now unused domain
TITLE format:
└── …

docs: Remove refs to discarded domain name

---

.github/CONTRIBUTING.md
app/src/views/PrivacyPolicy.vue

Because the documents haven't been updated in a while
- update them to reflect the current state
- make some language clearer

docs: Cleanup contributing guide and clarify privacy

---

app/android/app/build.gradle
app/package-lock.json
app/package.json
app/versionsync.mjs

TITLE format:
└── chore|content|docs|feat|fix|refactor|revert|style|test
MESSAGE format:
**Motivation - Why is this change necessary?**
Because
**Impact - How will this commit address …

chore: Release v1.0.3 build 30

---

app/package-lock.json
app/package.json
docs/architecture/architecture.md

Because vite has a security vuln we should address, ans some other deps are out of date,
- update all dependencies to latest

chore: Update dependencies

---

README.md
docs/index.md

Because the target demographic is imprecisely described,
- update the Seedlingo description on the documentation main page and in the README

docs: Update app description in docs

---

app/android/app/build.gradle
app/package-lock.json
app/package.json
app/src/AppHeader/components/AppHeader.vue
app/src/common/plugins/PlausibleAnalytics.ts
app/src/main.ts
app/src/views/ExerciseSession.vue
app/src/vite-env.d.ts
app/vite.config.ts

Because we need to rule out issues that emerge in earlier app versions,
- add tracking of app version
- add tracking of whether the app is run in a browser or wrapped as app

feat: Add tracking of app version

---

app/android/app/build.gradle

chore: Release v1.3.0

---

docs/.vuepress/theme/HomeFeatures.vue
docs/index.md
docs/package-lock.json
docs/package.json
docs/vuepress.config.ts

Because of a vulnerability in a dependency,
we have to update those deps anyway,
so we take a look at other deps that could use an update.
- update most dependencies to the latest version available

chore: Update dependencies for docs

---

app/src/AppHeader/components/AppHeader.vue

feat: Update logo in header to newest version

---

content/update-license-web-statements.js
content/valiate-asset-references.js

chore: Backport tools from English Demo version

---

README.md
app/README.md

docs: Include refs to English demo version

---

.github/workflows/codeql-analysis.yml

- I have read the [contributing guidelines](https://github.com/nodepa/seedlingo/blob/main/.github/CONTRIBUTING.md)

chore: Upgrade codeql-analysis to v2

---

docs/index.md
docs/vuepress.config.ts

docs: Update seedlingo.com landing to ref English content version
